DROP TABLE purchase;

CREATE TABLE purchase(
 POST_NO			 NUMERIC NOT NULL PRIMARY KEY,
 TICKET_TITLE        VARCHAR2(100),
 TICKET_IMAGE        VARCHAR2(800),
 BOOKING_DATE        VARCHAR2(20),
 CANCEL_DATE		 VARCHAR2(20),
 TICKET_PRICEALL     VARCHAR2(250),
 CONTENT_ID          NUMERIC  ,
 CONTENT_TYPEID      NUMERIC ,
 FLAG_BP			 VARCHAR2(20),
 REG_DATE            DATE,
 BUYER_ID			 VARCHAR2(50),
 BUYER_EMAIL		 VARCHAR2(50),
 BUYER_PHONE		 VARCHAR2(20),
 BUYER_NAME		 	 VARCHAR2(20)
);

CREATE SEQUENCE SEQ_PURCHASE_POST_NO START WITH 50000 INCREMENT BY 1;

COMMIT;

