DROP TABLE ticket;

CREATE TABLE ticket(
 POST_NO			 NUMERIC NOT NULL PRIMARY KEY,
 LAT       			 VARCHAR2(20),
 LNG        		 VARCHAR2(20),
 TICKET_TITLE        VARCHAR2(200),
 CONTENT_ID          NUMERIC,
 CONTENT_TYPEID      NUMERIC,
 TICKET_IMAGE		 VARCHAR2(800)
);

CREATE SEQUENCE SEQ_TICKET_POST_NO START WITH 80000 INCREMENT BY 1;

COMMIT;

